name: Deploy React App to GCS

on:
  push:
    branches: [ci-cd]
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest

    env:
      GCS_BUCKET: custody-backend-java-frontend
      GCP_PROJECT_ID: custody-backend-java

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install dependencies
        run: npm ci

      - name: Build the app
        run: npm run build

      - name: Authenticate SDK for `gcloud`-based steps
        uses: google-github-actions/auth@v1
        with:
          credentials_json: '${{ secrets.GCP_SA_KEY }}'

      - name: Set GCP project
        run: gcloud config set project $GCP_PROJECT_ID

      - name: Upload build folder to GCS
        uses: google-github-actions/upload-cloud-storage@v1
        with:
          path: build
          destination: ${{ env.GCS_BUCKET }}
          parent: false

      - name: Decode GCP key file
        run: echo "${{ secrets.GCP_SA_KEY_B64 }}" | base64 --decode > ${{ github.workspace }}/gcp-key.json

      - name: Authorize gsutil with service account
        run: |
          gcloud auth activate-service-account --key-file="${{ github.workspace }}/gcp-key.json"
          gcloud config set project $GCP_PROJECT_ID

      - name: Make all files public
        run: gsutil -m acl ch -r -u AllUsers:R gs://${{ env.GCS_BUCKET }}

      - name: Set bucket website config
        run: gsutil web set -m index.html -e 404.html gs://${{ env.GCS_BUCKET }}

      - name: Cleanup key file
        run: rm ${{ github.workspace }}/gcp-key.json
